/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2025-03-11 04:41:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/user/footer.jsp", Long.valueOf(1741588636299L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>AgroSeed</title>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!--// bootstrap-css -->\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!--// css -->\r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("<!-- //font-awesome icons -->\r\n");
      out.write("<!-- font -->\r\n");
      out.write("<link href=\"http://fonts.googleapis.com/css?family=Laila:300,400,500,600,700\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"http://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i\" rel=\"stylesheet\">\r\n");
      out.write("<!-- //font -->\r\n");
      out.write("<script src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t$(\".scroll\").click(function(event){\t\t\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#logo{\r\n");
      out.write("      text-shadow: 3px 2px brown;\r\n");
      out.write("      }\r\n");
      out.write(" .banner-slider\r\n");
      out.write(" {\r\n");
      out.write(" background-image: url(\"image/farmer.jpg\");\r\n");
      out.write(" padding-bottom: 2em;\r\n");
      out.write(" }\r\n");
      out.write("</style> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"banner\">\r\n");
      out.write("\t\t<div class=\"head\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-top\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t\t\t <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t  </button>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t <div class=\"navbar-brand logo \" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h1 class=\"animated wow pulse\" data-wow-delay=\".5s\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"index.html\" id=\"logo\">Agro<span>Seed</span></a></h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t\t <ul class=\"nav navbar-nav link-effect-4\">\r\n");
      out.write("\t\t\t\t\t\t\t    <li class=\"active\"><a href=\"index.html\" data-hover=\"Home\">Home</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t   <!-- <li><a href=\"about.html\" data-hover=\"About\">About </a> </li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"user/login.jsp\" data-hover=\"Farmer Login\">Farmer Login</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <a href=\"codes.html\" class=\"dropdown-toggle\" data-hover=\"services\" data-toggle=\"dropdown\">Services<b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t       <li><a href=\"land details.jsp\">Land details</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t       <li><a href=\"crop details.jsp\">Crop details</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t       <li><a href=\"monsoon details.jsp\">Monsoon details</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </ul>\r\n");
      out.write("\t\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"user/contact1.jsp\" data-hover=\"Contact\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div><!-- /.navbar-collapse -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"banner-slider\">\r\n");
      out.write("\t\t\t\t\t<div class=\"slider\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"callbacks_container\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"rslides callbacks callbacks1\" id=\"slider4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"jarallax agileits-banner-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"w3ls-banner-shadow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3>Basic Purpose</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Our goal is to help farmer grow more food with providing advanced informations</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"jarallax agileits-banner-info agileits-banner-info2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"w3ls-banner-shadow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3>About Us</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>A farming portal where the farmer can access all major informations anywhere, anytime by saving money and time</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"jarallax agileits-banner-info agileits-banner-info2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"w3ls-banner-shadow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3>Highlight</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>All the informations are up to date and well checked. In case of queries the farmer is most welcome to ask and suggest in the contact form</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t<script src=\"js/responsiveslides.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t// You can also use \"$(window).load(function() {\"\r\n");
      out.write("\t\t\t\t\t\t\t$(function () {\r\n");
      out.write("\t\t\t\t\t\t\t  // Slideshow 4\r\n");
      out.write("\t\t\t\t\t\t\t  $(\"#slider4\").responsiveSlides({\r\n");
      out.write("\t\t\t\t\t\t\t\tauto: true,\r\n");
      out.write("\t\t\t\t\t\t\t\tpager:true,\r\n");
      out.write("\t\t\t\t\t\t\t\tnav:false,\r\n");
      out.write("\t\t\t\t\t\t\t\tspeed: 1000,\r\n");
      out.write("\t\t\t\t\t\t\t\tnamespace: \"callbacks\",\r\n");
      out.write("\t\t\t\t\t\t\t\tbefore: function () {\r\n");
      out.write("\t\t\t\t\t\t\t\t  $('.events').append(\"<li>before event fired.</li>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tafter: function () {\r\n");
      out.write("\t\t\t\t\t\t\t\t  $('.events').append(\"<li>after event fired.</li>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t  });\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t </script>\r\n");
      out.write("\t\t\t\t\t\t<!--banner Slider starts Here-->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- //banner-slider -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"welcome\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"agileits-heading\">\r\n");
      out.write("\t\t\t\t<h2>Introduction</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"bs-example bs-example-tabs welcome-tabs\" role=\"tabpanel\" data-example-id=\"togglable-tabs\">\r\n");
      out.write("\t\t\t\t\t<ul id=\"myTab\" class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\" class=\"active\"><a href=\"#home\" id=\"home-tab\" role=\"tab\" data-toggle=\"tab\" aria-controls=\"home\" aria-expanded=\"true\">01</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\" class=\"\"><a href=\"#Feature1\" role=\"tab\" id=\"Feature1-tab\" data-toggle=\"tab\" aria-controls=\"Feature1\" aria-expanded=\"false\">02</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\" class=\"\"><a href=\"#Feature2\" role=\"tab\" id=\"Feature2-tab\" data-toggle=\"tab\" aria-controls=\"Feature2\" aria-expanded=\"false\">03</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\" class=\"\"><a href=\"#Feature3\" role=\"tab\" id=\"Feature3-tab\" data-toggle=\"tab\" aria-controls=\"Feature3\" aria-expanded=\"false\">04</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<div id=\"myTabContent\" class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane fade active in\" id=\"home\" aria-labelledby=\"home-tab\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"w3agile_tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-5 w3agile_tab_right w3agile_tab_right2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/7.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-7 w3agile_tab_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Home</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p> AgrooSeed empowers farmers and seeks to lift them out of poverty using cheap, affordable technology and democratizing the access to knowledge that can help them grow more food.\r\n");
      out.write("But today the world has amazing technology. The world also has a lot more knowledge of growing more food. Here we aim to make some of this available to our farmers easily.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane fade\" id=\"Feature1\" aria-labelledby=\"Feature1-tab\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3agile_tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-7 w3agile_tab_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>About</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>AgroSeed suggestions on which fertilizers and pesticides to use where and how much. It also tells about the water requirements of the crops. It also tells which crop, herb or vegetable is to be grown on what soil type and in which season.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-5 w3agile_tab_right w3agile_tab_right1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/6.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane fade\" id=\"Feature2\" aria-labelledby=\"Feature2-tab\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"w3agile_tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-5 w3agile_tab_right w3agile_tab_right2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/5.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-7 w3agile_tab_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Services</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>In Land details farmer can know about the features of his soil type and what crops are to be grown in them.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>In Crop details farmer can know all the deatils for his crop like its nature, water requirements, fertilizers and pesticides to use.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>In Crop types farmer can search for which crops to produce in which monsoon and arround what time to sow and harvest it.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane fade\" id=\"Feature3\" aria-labelledby=\"Feature3-tab\"><div class=\"w3agile_tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-7 w3agile_tab_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Contact</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Here a farmer can search for the sol testing locations and in case of any queries he can also contact the admin through messaging and will get the reply from him through call.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-5 w3agile_tab_right w3agile_tab_right1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"images/4.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<script src=\"js/jarallax.js\"></script>\r\n");
      out.write("\t<script src=\"js/SmoothScroll.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t/* init Jarallax */\r\n");
      out.write("\t\t$('.jarallax').jarallax({\r\n");
      out.write("\t\t\tspeed: 0.5,\r\n");
      out.write("\t\t\timgWidth: 1366,\r\n");
      out.write("\t\t\timgHeight: 768\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"../css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!--// bootstrap-css -->\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/style.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!--// css -->\r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link href=\"../css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("<!-- //font-awesome icons -->\r\n");
      out.write("<!-- font -->\r\n");
      out.write("<link href=\"http://fonts.googleapis.com/css?family=Laila:300,400,500,600,700\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"http://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i\" rel=\"stylesheet\">\r\n");
      out.write("<!-- //font -->\r\n");
      out.write("<script src=\"../js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t$(\".scroll\").click(function(event){\t\t\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"footer\" style=\"width:100%\">\r\n");
      out.write("\t\t<div class=\"footer-top\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-grids\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 footer-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-logo\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4><a href=\"index.html\">Agro<span>Seed</span></a></h4>\r\n");
      out.write("\t\t\t\t\t\t\t<p>Farmer Portal which insures them to make the best utilizaton and productivity of their land</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 footer-grid\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Navigation</h3>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t    <li> <a href=\"../index.jsp\">Home</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a href=\"about.html\">About</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a href=\"gallery.html\">Gallery</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a href=\"login.jsp\">Farmer Login</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <a href=\"codes.html\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Services<b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t       <li><a href=\"icons.html\">Land details</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t       <li><a href=\"\">Crop details</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </ul>\r\n");
      out.write("\t\t\t\t\t\t\t    </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li> <a href=\"contact1.jsp\">Contact</a> </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 footer-list\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Address</h3>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t   <li>Eiusmod Tempor inc </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>St Dolore Place,</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>San Francisco 56777 </li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 footer-list\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Phone Number</h3>\r\n");
      out.write("\t\t\t\t\t\t<ul >\r\n");
      out.write("\t\t\t\t\t\t\t<li>+2 123 456 789</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>+2 123 456 789</li>\r\n");
      out.write("\t\t     \t\t\t</ul><br/>\r\n");
      out.write("\t\t     \t\t\t<h3>Email ID</h3>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"w3agile_footer_grid_list\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mailto:example@email.com\">mail@example.com</a></li>\r\n");
      out.write("\t\t     \t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"../js/jarallax.js\"></script>\r\n");
      out.write("\t<script src=\"../js/SmoothScroll.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t/* init Jarallax */\r\n");
      out.write("\t\t$('.jarallax').jarallax({\r\n");
      out.write("\t\t\tspeed: 0.5,\r\n");
      out.write("\t\t\timgWidth: 1366,\r\n");
      out.write("\t\t\timgHeight: 768\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/move-top.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/easing.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
