/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2025-03-10 08:12:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;

public final class AdminLogIn_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/admin/../Connection.jsp", Long.valueOf(1741588636223L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Admin LogIn Panel</title>\r\n");
      out.write("<link href=\"../css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!--// bootstrap-css -->\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/style.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!--// css -->\r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link href=\"../css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("<!-- //font-awesome icons -->\r\n");
      out.write("<!-- font -->\r\n");
      out.write("<link href=\"http://fonts.googleapis.com/css?family=Laila:300,400,500,600,700\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"http://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i\" rel=\"stylesheet\">\r\n");
      out.write("<!-- //font -->\r\n");
      out.write("<script src=\"../js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.js\"></script>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t$(\".scroll\").click(function(event){\t\t\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#logo{\r\n");
      out.write("      text-shadow: 3px 2px brown;\r\n");
      out.write("      }\r\n");
      out.write("</style> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");

	
   Connection cn =null;
   Class.forName("com.mysql.jdbc.Driver");
   cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/agroseed","root","root");
	
 
   

  
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- header Start -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"banner\">\r\n");
      out.write("\t\t<div class=\"head\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-top\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t\t\t <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t  </button>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t <div class=\"navbar-brand logo \" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h1 class=\"animated wow pulse\" data-wow-delay=\".5s\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"index.html\" id=\"logo\">Agro<span>Seed</span></a></h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t\t <ul class=\"nav navbar-nav link-effect-4\">\r\n");
      out.write("\t\t\t\t\t\t\t    <li class=\"active\"><a href=\"AdminLogIn.jsp\" data-hover=\"Home\">Home</a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!--\t<li><a href=\"about.html\" data-hover=\"About\">About </a> </li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div><!-- /.navbar-collapse -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"clearfix\"></div>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<script src=\"../js/jarallax.js\"></script>\r\n");
      out.write("\t<script src=\"../js/SmoothScroll.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t/* init Jarallax */\r\n");
      out.write("\t\t$('.jarallax').jarallax({\r\n");
      out.write("\t\t\tspeed: 0.5,\r\n");
      out.write("\t\t\timgWidth: 1366,\r\n");
      out.write("\t\t\timgHeight: 768\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/move-top.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/easing.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<!-- header end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <div class=\"jarallax about-banner\" style=\"padding: .5em 0\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"agileits-heading about-heading\">\r\n");
      out.write("\t\t\t\t\t<h1>Admin Login Form</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\r\n");
      out.write("   <form action=\"\" class=\"needs-validation\" novalidate>\r\n");
      out.write("    \r\n");
      out.write("   <div class=\"form-group\">\r\n");
      out.write("      <label for=\"uname\">Email Id</label>\r\n");
      out.write("      <input type=\"tel\" class=\"form-control\" id=\"adhaar\" name=\"adhaar\"  required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"uname\">Password:</label>\r\n");
      out.write("      <input type=\"password\" class=\"form-control\" name=\"pass\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("\t \r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-primary\" name=\"Login\">Login</button>\r\n");
      out.write("    \r\n");
      out.write("    ");

       
        
    
    	try{
    		
    		if(request.getParameter("Login")!= null){
    			Statement st1 =cn.createStatement();
		    	ResultSet rs =st1.executeQuery("select * from admin where  EmailId='"+request.getParameter("adhaar")+"' and Password='"+request.getParameter("pass")+"'");
		    	if(rs.next()){
		    		response.sendRedirect("viewcontact.jsp");
		    	}
		    	/**if(rs.next())
		    	{
		    		out.println("You are login Successfully ! ");
		    	}*/
		    	else
		    	{
		    		out.println("! Please Enter Valid details. ");
		    	}
		    	 
		    	
		   }
    		
    	
    	
    	}catch(Exception ex)
    	{
    		out.println(ex);
    	}
   
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </form>\r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("// Disable form submissions if there are invalid fields\r\n");
      out.write("(function() {\r\n");
      out.write("  'use strict';\r\n");
      out.write("  window.addEventListener('load', function() {\r\n");
      out.write("    // Get the forms we want to add validation styles to\r\n");
      out.write("    var forms = document.getElementsByClassName('needs-validation');\r\n");
      out.write("    // Loop over them and prevent submission\r\n");
      out.write("    var validation = Array.prototype.filter.call(forms, function(form) {\r\n");
      out.write("      form.addEventListener('submit', function(event) {\r\n");
      out.write("        if (form.checkValidity() === false) {\r\n");
      out.write("          event.preventDefault();\r\n");
      out.write("          event.stopPropagation();\r\n");
      out.write("        }\r\n");
      out.write("        form.classList.add('was-validated');\r\n");
      out.write("      }, false);\r\n");
      out.write("    });\r\n");
      out.write("  }, false);\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
